name: Android Tests - Sauce Labs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mobile-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Definir variáveis Sauce Labs
        run: |
          echo "SAUCE_USERNAME=${{ secrets.SAUCE_USERNAME }}" >> $GITHUB_ENV
          echo "SAUCE_ACCESS_KEY=${{ secrets.SAUCE_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Instalar dependências
        run: ./gradlew build --refresh-dependencies

      - name: Rodar testes no Sauce Labs
        run: ./gradlew clean test -Dexecution.mode=sauce
